# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    posts.service:
            class: PostsBundle\Services\PostsServices\Posts
            arguments: ['@providers.facebook']

    providers.facebook_factory:
            class: PostsBundle\Factory\FacebookManagerFactory

    providers.facebook:
            class:     PostsBundle\Services\Providers\FacebookManager\FacebookManager
            factory: 'providers.facebook_factory:createFacebookManager'
            arguments: ['%facebook%']
